name: blade-v9-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell Core
        uses: PowerShell/PowerShell@v1
        with:
          version: '7.4.x'

      - name: Build addon (zip + install to APPDATA)
        shell: pwsh
        run: |
          & ".\tools\Make_V9.ps1" -Verbose

      - name: Smoke tests
        shell: pwsh
        run: |
          & ".\tools\Test_V9.ps1"

      - name: Create dated dist zip
        shell: pwsh
        run: |
          & ".\tools\Release_V9.ps1"

      - name: Find latest dist zip path
        id: dist
        shell: pwsh
        run: |
          $zip = Get-ChildItem ".\dist" -Filter "blade_v9_*.zip" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          "zip_path=$($zip.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Upload artifact (CI)
        uses: actions/upload-artifact@v4
        with:
          name: blade_v9_dist_zip
          path: ${{ steps.dist.outputs.zip_path }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ${{ steps.dist.outputs.zip_path }}
